# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 240)
        MainWindow.setMinimumSize(QtCore.QSize(480, 240))
        MainWindow.setMaximumSize(QtCore.QSize(480, 240))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_box = QtWidgets.QTextEdit(self.centralwidget)
        self.text_box.setGeometry(QtCore.QRect(10, 30, 161, 71))
        self.text_box.setObjectName("text_box")
        self.main_exec = QtWidgets.QPushButton(self.centralwidget)
        self.main_exec.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.main_exec.setObjectName("main_exec")
        self.mode_t2q = QtWidgets.QRadioButton(self.centralwidget)
        self.mode_t2q.setGeometry(QtCore.QRect(190, 90, 91, 18))
        self.mode_t2q.setChecked(False)
        self.mode_t2q.setObjectName("mode_t2q")
        self.mode_q2t = QtWidgets.QRadioButton(self.centralwidget)
        self.mode_q2t.setGeometry(QtCore.QRect(190, 110, 91, 18))
        self.mode_q2t.setObjectName("mode_q2t")
        self.textbox_label = QtWidgets.QLabel(self.centralwidget)
        self.textbox_label.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.textbox_label.setObjectName("textbox_label")
        self.qr_label = QtWidgets.QLabel(self.centralwidget)
        self.qr_label.setGeometry(QtCore.QRect(300, 10, 71, 16))
        self.qr_label.setObjectName("qr_label")
        self.encoding_label = QtWidgets.QLabel(self.centralwidget)
        self.encoding_label.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.encoding_label.setObjectName("encoding_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(80, 110, 20, 91))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.encoding_utf8 = QtWidgets.QRadioButton(self.centralwidget)
        self.encoding_utf8.setGeometry(QtCore.QRect(10, 130, 71, 18))
        self.encoding_utf8.setObjectName("encoding_utf8")
        self.encoding_ascii = QtWidgets.QRadioButton(self.centralwidget)
        self.encoding_ascii.setGeometry(QtCore.QRect(10, 150, 71, 18))
        self.encoding_ascii.setObjectName("encoding_ascii")
        self.encoding_shift = QtWidgets.QRadioButton(self.centralwidget)
        self.encoding_shift.setGeometry(QtCore.QRect(10, 170, 71, 18))
        self.encoding_shift.setObjectName("encoding_shift")
        self.export_exec = QtWidgets.QPushButton(self.centralwidget)
        self.export_exec.setGeometry(QtCore.QRect(190, 130, 75, 23))
        self.export_exec.setObjectName("export_exec")
        self.import_exec = QtWidgets.QPushButton(self.centralwidget)
        self.import_exec.setGeometry(QtCore.QRect(190, 60, 75, 23))
        self.import_exec.setObjectName("import_exec")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(110, 110, 51, 16))
        self.size_label.setObjectName("size_label")
        self.size_auto_button = QtWidgets.QRadioButton(self.centralwidget)
        self.size_auto_button.setGeometry(QtCore.QRect(110, 130, 71, 18))
        self.size_auto_button.setObjectName("size_auto_button")
        self.size_manual_button = QtWidgets.QRadioButton(self.centralwidget)
        self.size_manual_button.setGeometry(QtCore.QRect(110, 150, 71, 18))
        self.size_manual_button.setObjectName("size_manual_button")
        self.size_slider = QtWidgets.QSlider(self.centralwidget)
        self.size_slider.setGeometry(QtCore.QRect(110, 170, 160, 16))
        self.size_slider.setMinimum(1)
        self.size_slider.setMaximum(42)
        self.size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.size_slider.setObjectName("size_slider")
        self.pixmap_label = QtWidgets.QLabel(self.centralwidget)
        self.pixmap_label.setGeometry(QtCore.QRect(300, 30, 161, 161))
        self.pixmap_label.setText("")
        self.pixmap_label.setScaledContents(True)
        self.pixmap_label.setObjectName("pixmap_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 18))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.export_exec_2 = QtWidgets.QAction(MainWindow)
        self.export_exec_2.setObjectName("export_exec_2")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menuFiles.addAction(self.action_exit)
        self.menuFiles.addAction(self.export_exec_2)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "simpleQRtool-NG"))
        self.main_exec.setText(_translate("MainWindow", "Convert"))
        self.mode_t2q.setText(_translate("MainWindow", "Text to QR"))
        self.mode_q2t.setText(_translate("MainWindow", "QR to Text"))
        self.textbox_label.setText(_translate("MainWindow", "Text box(In & Out)"))
        self.qr_label.setText(_translate("MainWindow", "QR Code"))
        self.encoding_label.setText(_translate("MainWindow", "Encoding"))
        self.encoding_utf8.setText(_translate("MainWindow", "UTF-8"))
        self.encoding_ascii.setText(_translate("MainWindow", "ASCII"))
        self.encoding_shift.setText(_translate("MainWindow", "Shift JIS"))
        self.export_exec.setText(_translate("MainWindow", "Export"))
        self.import_exec.setText(_translate("MainWindow", "Import"))
        self.size_label.setText(_translate("MainWindow", "Size"))
        self.size_auto_button.setText(_translate("MainWindow", "Auto"))
        self.size_manual_button.setText(_translate("MainWindow", "Manual"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.export_exec_2.setText(_translate("MainWindow", "Export to PNG"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
